name: "Build and push"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  # build:
  #   name: build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       version: [base, copy]
  #       target: [x86_64-unknown-linux-gnu]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Rust
  #       uses: actions-rust-lang/setup-rust-toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: ${{ matrix.target }}
  #     - name: Build
  #       run: cargo build --release --target ${{ matrix.target }}
  #     - name: Archive
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ${{ matrix.target }}-${{ matrix.version }}-release
  #         path: target/release/fish

  docker:
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: 0
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Login to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Git commit timestamps
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/skofaljaz/fish:latest
          push: true
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
